version: '3'

services:
  matomo-db:
    image: mariadb:10.11
    command: --max-allowed-packet=64MB
    restart: always
    volumes:
      - matomo-db:/var/lib/mysql:Z
    environment:
      - MYSQL_ROOT_PASSWORD=changeme
      - MARIADB_AUTO_UPGRADE=1
      - MARIADB_DISABLE_UPGRADE_BACKUP=1
      - MYSQL_PASSWORD=matomodev
      - MYSQL_DATABASE=matomo
      - MYSQL_USER=matomo
    env_file:
      - ./dev-data/db.env
    networks:
      - matomo
  matomo-app:
    # matomo locally is only working directly and not via traefik for now
    image: matomo
    restart: always
    volumes:
      #     - ./config:/var/www/html/config:z
      #     - ./logs:/var/www/html/logs:z
      - matomo-app:/var/www/html:z
    environment:
      - MATOMO_DATABASE_HOST=matomo-db
    env_file:
      - ./dev-data/db.env
    ports:
      - "8100:80"
    networks:
      - matomo
  boudicca-eventdb:
    image: docker.io/boudicca/eventdb:latest
    ports:
      - "8081:8080"
    environment:
      - "BOUDICCA_STORE_PATH=/boudicca.store/boudicca.store"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-router"
      - "traefik.http.routers.eventdb.rule=PathPrefix(`/ingest`) || PathPrefix(`/entries`)"
      - "traefik.http.routers.eventdb.entrypoints=web"
      - "traefik.http.services.eventdb.loadbalancer.server.port=8080"
    volumes:
      - ./boudicca.store/:/boudicca.store/:Z
    networks:
      - traefik-router
  boudicca-search:
    image: docker.io/boudicca/search:latest
    depends_on:
      - boudicca-eventdb
    environment:
      - BOUDICCA_EVENTDB_URL=http://boudicca-eventdb:8080
      - BOUDICCA_LOCALMODE=true
    ports:
      - "8082:8080"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-router"
      - "traefik.http.routers.search.rule=PathPrefix(`/api/search`)"
      - "traefik.http.routers.search.priority=30"
      - "traefik.http.routers.search.entrypoints=web"
      - "traefik.http.routers.search.middlewares=admin-stripprefix"
      - "traefik.http.middlewares.admin-stripprefix.stripprefix.prefixes=/api/search"
      - "traefik.http.services.search.loadbalancer.server.port=8080"
    networks:
      - traefik-router
  boudicca-ical:
    # minimal ical query: http://localhost:3050/ical/calendar.ics?query=%22startDate%22%20after%202024-01-01%20and%20%22startDate%22%20after%202025-01-01
    image: git.twatzl.eu/twatzl/boudicca-ical
    depends_on:
      - boudicca-search
    environment:
      - BOUDICCA_SEARCH_URL=http://boudicca-search:8080
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.boudicca-ical.rule=PathPrefix(`/ical`)"
      - "traefik.http.routers.boudicca-ical.entrypoints=web"
      - "traefik.http.routers.boudicca-ical.middlewares=ical-stripprefix"
      - "traefik.http.middlewares.ical-stripprefix.stripprefix.prefixes=/ical"
    networks:
      - traefik-router
  museum-railway-events-backend:
    image: git.twatzl.eu/twatzl/museum-railway-events-backend:latest
    ports:
      - "8080:8080"
    environment:
      - "IMAGE_IMG_PROXY_URL=http://imgproxy:8080"
      - "IMAGE_SIGNING_KEY=c265ea162df50eb1793cfd4547e1c0d8cffa61e3abdaf9e075c3376bdae53ec731bc6a9d0c743e4242071aabf61a9a290799c1bb96c26ba827730f7371f908c9"
      - "IMAGE_SIGNING_SALT=d531871747288265e6144698350f915a781005ba8dd7ed6fcf28634cec4a8c47744d37e830b5e5942c3c2a3e0758a00a6f2d2f847afb1728e31d1e10beb44d87"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-router"
      - "traefik.http.routers.backend.rule=PathPrefix(`/api/`) || Path(`/imgcache`)"
      - "traefik.http.routers.backend.priority=20"
      - "traefik.http.routers.backend.entrypoints=web"
      - "traefik.http.services.backend.loadbalancer.server.port=8080"
    networks:
      - traefik-router
  museum-railway-events-eventcollectors:
    image: git.twatzl.eu/twatzl/museum-railway-events-eventcollectors:latest
    depends_on:
      - boudicca-eventdb
    ports:
      - "8083:8083"
    networks:
      - traefik-router
  museum-railway-events-web:
    image: git.twatzl.eu/twatzl/museum-railway-events-web:latest
    depends_on:
      - boudicca-eventdb
      - boudicca-search
      #- museum-railway-events-backend
    environment:
      NUXT_BACKEND_API_PROXY_URL: "http://host.containers.internal:3050/"
      NUXT_BOUDICCA_SEARCH_API_PROXY_URL: "http://host.containers.internal:3050/"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-router"
      - "traefik.http.routers.frontend.rule=PathPrefix(`/`)"
      - "traefik.http.routers.frontend.entrypoints=web"
      - "traefik.http.routers.frontend.priority=10"
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"
    ports:
      - "3010:3000"
    networks:
      - traefik-router
  imgproxy:
    image: darthsim/imgproxy:v3.27.1
    ports:
      - "8090:8080"
    environment:
      - IMGPROXY_KEY=c265ea162df50eb1793cfd4547e1c0d8cffa61e3abdaf9e075c3376bdae53ec731bc6a9d0c743e4242071aabf61a9a290799c1bb96c26ba827730f7371f908c9
      - IMGPROXY_SALT=d531871747288265e6144698350f915a781005ba8dd7ed6fcf28634cec4a8c47744d37e830b5e5942c3c2a3e0758a00a6f2d2f847afb1728e31d1e10beb44d87
    networks:
      - traefik-router
  reverse-proxy:
    # The official v3 Traefik docker image
    image: traefik:v3.2.3
    restart: unless-stopped
    # needed to access docker socket on linux machines
    privileged: true
    command:
      # take config from commandline.
      - "--configFile=/config/traefik.yml"
      # Do not expose containers unless explicitly told so
      - "--providers.docker.exposedbydefault=false"
    labels:
      # this is needed as we did the --providers.docker.exposedbydefault=false
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-router"
      - "traefik.http.routers.traefik.rule=PathPrefix(`/dashboard`) || PathPrefix(`/api`)"
      - "traefik.http.routers.traefik.priority=10"
      - "traefik.http.services.traefik.loadbalancer.server.port=3090"
      - "traefik.http.routers.traefik.service=api@internal"
    ports:
      # 80 is our http port for testing purposes
      - "3050:80"
      # 3051 simulates a https port, we don't really use it
      - "3051:3051"
      # The Web UI (enabled by --api.insecure=true)
      - "3090:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      #- /var/run/docker.sock:/var/run/docker.sock:Z
      - /run/user/1000/podman/podman.sock:/var/run/docker.sock:Z
      - ./traefik/config/:/config/:Z
      - ./traefik/logs/:/logs/:Z
    networks:
      - traefik-router


volumes:
  matomo-db:
  matomo-app:

networks:
  matomo:
  traefik-router: