package at.museumrailwayevents.model.conventions

object MuseumLocationId {
    const val PBV = "pbv"
    const val RHEINSCHAUEN = "rheinschauen"
    const val OEGEG_NORMALSPUR = "oegeg_normalspur"
    const val OEGEG_SCHMALSPUR = "oegeg_schmalspur"
    const val OEGEG_SCHIFFFAHRT = "oegeg_schifffahrt"
    const val HOELLENTALBAHN = "hoellentalbahn"
    const val YBBSTALBAHN = "ybbstalbahn"
    const val OESEK = "oesek"
    const val WAELDERBAEHNLE = "waelderbaehnle"
    const val EBFL = "ebfl"
    const val MH6 = "mh6"
    const val SBM = "sbm"
    const val FLASCHERLZUG = "flascherlzug"
    const val TAURACHBAHN = "taurachbahn"
    const val WALDVIERTELBAHN = "waldviertelbahn"
    const val MARIAZELLERBAHN = "mariazellerbahn"
    const val NBIK_EISENBAHN = "nbik_eisenbahn"
    const val NBIK_SCHIFF = "nbik_schiff"
    const val NBIK_HISTORAMA = "nbik_historama"
    const val NBIK_VERKEHRSMUSEUM = "nbik_verkehrsmuseum"
    const val NBIK_TRAM = "nbik_tram"
    const val EBM_SCHWECHAT = "ebm_schwechat"
}