// TODO: this should be generated by the openfetch client; not?
export interface Location {
    lat: number | undefined,
    lon: number | undefined,
    country: string,
    state: string,
    street: string,
    city: string | undefined,
    zipCode: string | undefined,
}

// TODO: this should be generated by the openfetch client; not?
export interface MuseumLocation {
    name: string;
    type: string;
    operatorId: string;
    locationId: string;
    webUrl: string;
    description: string;
    imageName: string;
    eventCollectorType: string;
    eventCollectionComment: string;
    location: Location;
}

// TODO: this should be generated by the openfetch client; not?
export interface MuseumEvent {
    name: string;
    description: string;
    eventCategory: string;
    date: Date;
    url: string;
    pictureUrl: string | undefined;
    pictureAltText: string | undefined;
    pictureCopyright: string | undefined;
    locomotiveType: string | undefined;
    locationId: string;
    operatorId: string;
    location: MuseumLocation | undefined;
}

export interface EventFilterSettings {
    fromDate?: Date | undefined,
    toDate?: Date | undefined,
    tagFilters?: EventTagFilterOption[],
    locationId?: string | undefined
}

export interface EventTagFilterOption {
    key: string,
    options: string[],
}

export interface FiltersResponse {
    [index: string]: string[];
}