// TODO: find a way to share this from the api package

export enum VehicleType {
    DIESEL_TRAIN = "diesel_train",
    STEAM_TRAIN = "steam_train",
    ELECTRIC_TRAIN = "electric_train",
    TRAM = "tram",
    SHIP = "ship",
}

export enum MuseumEventRegistration {
    FREE = "free", // free
    REGISTRATION = "registration", // free, but requires registration
    PRE_SALES_ONLY = "pre-sales-only",
    RESERVATION_RECOMMENDED = "reservation-recommended",
    PRIVATE_EVENT = "private-event", // not in use at the moment, but could be useful for events like photo trains
    TICKET = "ticket",
}

export enum RecurrenceType {
    REGULARLY = "regularly",
    RARELY = "rarely",
    ONCE = "once",
}

export enum OperationType {
    VOLUNTEER = "volunteer_run",
    COMMERCIAL = "commercial",
}

export enum MuseumEventCategory {
    SPECIAL_TRIP = "special_trip", // Sonderfahrt - excursion on public rails or a special event on the museum railway
    RAILWAY_MUSEUM = "railway_museum", // Museum - opening day of a museum, for museums without regular opening days or special events
    MUSEUM_RAILWAY = "museum_railway", // Museumsbahn - running day of a dedicated museum railway
    MUSEUM_EVENT = "museum_event", // Veranstaltung - besondere Veranstaltung, Konzert etc.
    MODEL_RAILWAY = "model_railway", // Modellbahn - not in use at the moment
}

// TODO: this should be generated by the openfetch client; not?
export interface Location {
    lat: number | undefined,
    lon: number | undefined,
    country: string,
    state: string,
    street: string,
    city: string | undefined,
    zipCode: string | undefined,
}

// TODO: this should be generated by the openfetch client; not?
export interface MuseumLocation {
    name: string;
    type: string;
    operatorId: string;
    locationId: string;
    webUrl: string;
    description: string;
    imageName: string;
    eventCollectorType: string;
    eventCollectionComment: string;
    location: Location;
}

// TODO: this should be generated by the openfetch client; not?
export interface MuseumEvent {
    name: string;
    description: string;
    eventCategory: MuseumEventCategory | undefined;
    date: Date;
    url: string;
    pictureUrl: string | undefined;
    pictureAltText: string | undefined;
    pictureCopyright: string | undefined;
    vehicleType: VehicleType | undefined;
    registration: MuseumEventRegistration | undefined;
    recurrenceType: RecurrenceType | undefined;
    operationType: OperationType | undefined;
    locationId: string;
    operatorId: string;
    tags: string[];
    location: MuseumLocation | undefined;
}

export interface EventFilterSettings {
    fromDate?: Date | undefined,
    toDate?: Date | undefined,
    tagFilters?: EventTagFilterOption[],
    locationId?: string | undefined
}

export interface EventTagFilterOption {
    key: string,
    options: string[],
}

export interface FiltersResponse {
    [index: string]: string[];
}