[versions]
kotlin = "2.1.0"
ktor = "3.1.1"
logback = "1.5.6"
spring-openapi-starter = "2.8.5"
spring = "6.4.3"
spring-boot = "3.4.3"
org-springframework-boot-gradle-plugin = "3.4.3"
boudicca = "0.6.0"
jackson = "2.18.3"
jackson-databind-nullable = "0.2.6"
junit-jupiter = "5.12.0"
assertk = "0.28.1"
mockk = "1.13.17"
slf4j = "2.0.17"
spring-mockk = "4.0.2"
graalvm = "0.10.5"
biweekly = "0.6.8"
handlebars = "4.5.0"
kotlin-logging = "7.0.13"
otel = "1.57.0"
otel-instrumentation = "2.23.0-alpha"

[libraries]
spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web", version.ref = "spring-boot" }
spring-boot-starter-security = { module = "org.springframework.boot:spring-boot-starter-security", version.ref = "spring-boot" }
spring-security-test = { module = "org.springframework.security:spring-security-test", version.ref = "spring" }
spring-openapi-starter = { module = "org.springdoc:springdoc-openapi-starter-webmvc-ui", version.ref = "spring-openapi-starter" }
spring-boot-devtools = { module = "org.springframework.boot:spring-boot-devtools", version.ref = "spring-boot" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test", version.ref = "spring-boot" }

kotlin-stdlib = {module ="org.jetbrains.kotlin:kotlin-stdlib"}
kotlin-reflect = {module ="org.jetbrains.kotlin:kotlin-reflect"}

slf4j = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }

boudicca-eventdb-openapi = {module ="events.boudicca:eventdb-openapi", version.ref = "boudicca"}
boudicca-commonmodel = {module ="events.boudicca:common-model", version.ref = "boudicca"}
boudicca-fetcherlib = {module ="events.boudicca:fetcher-lib", version.ref = "boudicca"}
# TODO: enable again once published by boudicca
# boudicca-dateparserlib = {module ="events.boudicca:dateparser-lib", version.ref = "boudicca"}
boudicca-publisher-client = {module ="events.boudicca:publisher-client", version.ref = "boudicca"}
boudicca-ingest-client = {module ="events.boudicca:ingest-client", version.ref = "boudicca"}
boudicca-enricher-client = {module ="events.boudicca:enricher-client", version.ref = "boudicca"}
boudicca-eventcollector-client = {module ="events.boudicca:eventcollector-client", version.ref = "boudicca"}
boudicca-remotecollector-client = {module ="events.boudicca:remote-collector-client", version.ref = "boudicca"}

kotlin-logging = { module = "io.github.oshai:kotlin-logging-jvm", version.ref = "kotlin-logging" }
kotlin-csv-jvm = {module ="com.github.doyaaaaaken:kotlin-csv-jvm", version="1.9.3"}

# todo: kinda wanna get rid of jackson in favor of kotlinx.serialization
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version = "1.8.0" }
jackson-core = { module = "com.fasterxml.jackson.core:jackson-core", version.ref = "jackson" }
jackson-annotations = { module = "com.fasterxml.jackson.core:jackson-annotations", version.ref = "jackson" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
jackson-databind-jsr310 = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jsr310", version.ref = "jackson" }
jackson-module-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref = "jackson" }

jackson-databind-nullable = { module = "org.openapitools:jackson-databind-nullable", version.ref = "jackson-databind-nullable" }


ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-client-engine-java = { module = "io.ktor:ktor-client-java", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }

logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }

junit-jupiter-bom = { module = "org.junit:junit-bom", version.ref = "junit-jupiter" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
assertk = { module = "com.willowtreeapps.assertk:assertk", version.ref = "assertk" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
spring-mockk = { module = "com.ninja-squad:springmockk", version.ref = "spring-mockk" }

biweekly = { module = "net.sf.biweekly:biweekly", version.ref = "biweekly" }

handlebars = { module = "com.github.jknack:handlebars", version.ref = "handlebars" }
handlebars-springmvc = { module = "com.github.jknack:handlebars-springmvc", version.ref = "handlebars" }

micrometer-core = { module = "io.micrometer:micrometer-core", version = "1.16.1" }
micrometer-otel-bridge = { module = "io.micrometer:micrometer-tracing-bridge-otel", version = "1.6.1" }
otel-api = { module = "io.opentelemetry:opentelemetry-api", version.ref = "otel" }
otel-sdk = { module = "io.opentelemetry:opentelemetry-sdk", version.ref = "otel" }
otel-exporter = { module = "io.opentelemetry:opentelemetry-exporter-otlp", version.ref = "otel" }
otel-semconv = { module = "io.opentelemetry.semconv:opentelemetry-semconv", version = "1.37.0" }
otel-java-httpclient = { module = "io.opentelemetry.instrumentation:opentelemetry-java-http-client", version.ref = "otel-instrumentation" }
otel-micrometer = { module = "io.opentelemetry.instrumentation:opentelemetry-micrometer-1.5", version.ref = "otel-instrumentation" }
otel-logback = { module = "io.opentelemetry.instrumentation:opentelemetry-logback-appender-1.0", version.ref = "otel-instrumentation" }

google-api-client = { module = "com.google.api-client:google-api-client", version = "2.7.2" }
google-auth-library-oauth2-http = { module = "com.google.auth:google-auth-library-oauth2-http", version = "1.33.1" }
google-api-services-sheets = { module = "com.google.apis:google-api-services-sheets", version = "v4-rev20250211-2.0.0" }

org-jetbrains-kotlin-jvm-gradle-plugin = { module = "org.jetbrains.kotlin.jvm:org.jetbrains.kotlin.jvm.gradle.plugin", version.ref = "kotlin" }
org-jetbrains-kotlin-plugin-spring-gradle-plugin = { module = "org.jetbrains.kotlin.plugin.spring:org.jetbrains.kotlin.plugin.spring.gradle.plugin", version.ref = "kotlin" }
org-jetbrains-kotlin-plugin-serialization-plugin = { module = "org.jetbrains.kotlin.plugin.serialization:org.jetbrains.kotlin.plugin.serialization.gradle.plugin", version.ref = "kotlin" }
org-springframework-boot-gradle-plugin = { module = "org.springframework.boot:org.springframework.boot.gradle.plugin", version.ref = "org-springframework-boot-gradle-plugin" }
graalvm-native-plugin = { module = "org.graalvm.buildtools:native-gradle-plugin", version.ref="graalvm" }

[bundles]

gradle-plugins = [
    "org-jetbrains-kotlin-jvm-gradle-plugin",
    "org-jetbrains-kotlin-plugin-spring-gradle-plugin",
    "org-jetbrains-kotlin-plugin-serialization-plugin",
    "org-springframework-boot-gradle-plugin",
    "graalvm-native-plugin"
]
