openapi: 3.0.1
info:
  version: "0.2.0"
  title: "museum-railway-backend"
tags:
- name: "Museum Railway Events Locations API"
- name: "Museum Railway Events Operators API"
paths:
  /api/manage/reloadData:
    post:
      tags:
        - management-controller
      operationId: clearCaches
      responses:
        "200":
          description: OK
  /imgcache:
    get:
      tags:
        - image-caching-proxy-controller
      operationId: getImage
      parameters:
        - name: url
          in: query
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            image/jpeg:
              schema:
                type: string
                format: byte
            image/png:
              schema:
                type: string
                format: byte
  /api/operator:
    get:
      tags:
        - operators-controller
      operationId: allOperators
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MuseumOperator'
  /api/location:
    get:
      tags:
        - locations-controller
      operationId: allLocations
      parameters:
        - name: operatorId
          in: query
          required: false
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MuseumLocation'
components:
  schemas:
    Location:
      required:
        - country
        - state
        - street
      type: object
      properties:
        lat:
          type: number
          format: float
        lon:
          type: number
          format: float
        country:
          type: string
        state:
          type: string
        street:
          type: string
        city:
          type: string
        zipCode:
          type: string
    MuseumOperator:
      required:
        - description
        - identifier
        - imageName
        - location
        - name
        - webUrl
      type: object
      properties:
        name:
          type: string
        identifier:
          type: string
        webUrl:
          type: string
        description:
          type: string
        imageName:
          type: string
        location:
          $ref: '#/components/schemas/Location'
    MuseumLocation:
      required:
        - description
        - eventCollectionComment
        - eventCollectorType
        - imageName
        - location
        - locationId
        - name
        - operatorId
        - type
        - webUrl
      type: object
      properties:
        name:
          type: string
        type:
          type: string
          enum:
            - Museum
            - Modellbahn
            - Veranstaltung
            - Museumsbahn
            - Sonderfahrten
            - Station
        operatorId:
          type: string
        locationId:
          type: string
        webUrl:
          type: string
        description:
          type: string
        imageName:
          type: string
        eventCollectorType:
          type: string
        eventCollectionComment:
          type: string
        location:
          $ref: '#/components/schemas/Location'
